@startmindmap
+ Projekte
++ Definition
+++ Ein Projekt ist ein zeitlich begrenztes Vorhaben.
+++ Ein Projekt schafft ein einzigartiges Produkt / eine Dienstleistung / ein Ergebnis.
-- Kriterien
--- Einmaligkeit
---- einzigartig
---- spezifisches Ziel
---- definierter Zeitrahmen
--- Komplexität
---- komplexer als routinemäßige Aufgaben
---- sorgfältige Planung und Organisation notwendig
--- Ressourcen
---- Budget
---- Personal
---- Materialien
---- Technologie
--- Interdisziplinär
---- verschiedene Fachbereiche
---- Teams nur für das Projekt zusammengestellt
--- Risiko
---- Ergebnis nicht vorhersehbar
---- Projekte können scheitern
--- Projektmanagement
---- gezieltes Management notwendig
---- Initiierung
---- Planung
---- Durchführung
---- Überwachung
---- Abschluss
@endmindmap