@startmindmap
+[#LightCoral] Merkmale für Kundengruppen
++ Demografische Merkmale
+++ Alter
+++ Geschlecht
+++ Einkommen
+++ Beruf
+++ Bildungsniveau
+++ Familienstand
+++ Wohnort
++ Geografische Merkmale
+++ Region
+++ Land
+++ Stadt
+++ Klima
++ Psychografische Merkmale
+++ Lebensstil
+++ Interessen und Hobbys
+++ Werte und Überzeugungen
+++ Einstellungen
+++ Persönlichkeitstypen
++ Verhaltensbasierte Merkmale
+++ Kaufverhalten
+++ Markenloyalität
+++ Nutzung bestimmter Produkte oder Dienstleistungen
+++ Kaufmotivationen
+++ Online-Verhalten (z.B. Social-Media-Nutzung)
++ Soziodemografische Merkmale
+++ Ethnische Zugehörigkeit
+++ Religion
+++ Sprache
++ Technografische Merkmale
+++ Gerätetypen (z.B. Smartphone, Tablet, Desktop)
+++ Internetnutzung (z.B. Mobile Data, Breitband)
-- Firmenbezogene Merkmale (B2B)
--- Unternehmensgröße
--- Branche
--- Umsatz
--- Standort
-- Lebensereignisse
--- Hochzeit
--- Geburt eines Kindes
--- Ruhestand
--- ...
-- Herausforderungen und Bedürfnisse
--- Schmerzpunkte und Herausforderungen Ihrer Zielgruppe
--- Welche Bedürfnisse haben sie, die Ihr Produkt oder Ihre Dienstleistung erfüllen kann?
-- Kommunikationskanäle
--- Wo und wie erreichen Sie Ihre Zielgruppe am besten?
--- bspw. Social Media, E-Mail, Printmedien oder persönliche Treffen
-- Kaufzyklus und Entscheidungsprozess
--- Zu welchem Zeitpunkt im Kaufzyklus (Erkundung, Bewertung, Kauf) befinden sich Ihre potenziellen Kunden?
--- Welche Einflussfaktoren beeinflussen ihre Kaufentscheidungen?
-- Budget und Kaufkraft
--- Wie viel Geld sind Ihre Zielgruppen bereit auszugeben?
--- Welche finanziellen Ressourcen haben sie?
-- Verbraucherverhalten
--- Welche Produkte oder Dienstleistungen verwenden sie bereits?
--- Welche Gewohnheiten und Vorlieben haben sie?
-- Soziale Netzwerke und Gemeinschaften
--- Welchen sozialen Gruppen oder Gemeinschaften gehören sie an?
--- Wo und wie tauschen sie Informationen aus?
-- Kulturelle Merkmale
--- Kulturelle Hintergründe und Unterschiede, die Einfluss auf das Kaufverhalten haben können
@endmindmap