@startmindmap
+[#LightCoral] Ergonomie am Arbeitsplatz
++ Sitzposition
+++ Stuhl bequem, Unterstützung des Rückens
+++ Füße flach auf dem Boden / auf der Fußstütze
+++ Knie im 90-Grad-Winkel
++ Tischhöhe
+++ Ellenbogen im 90-Grad Winkel
+++ Sitzposition zur Tastatur beachten
++ Bildschirmposition
+++ oberer Bildschirmrand auf Augenhöhe oder leicht darunter
+++ Abstand zwischen Augen und Bildschirm ca. 50-70 cm
++ Tastatur und Maus
+++ Flach auf dem Tisch liegend
+++ Handgelenke in neutraler Haltung
+++ Maus leicht erreichbar
+++ Überanstrengung der Handgelenke vermeiden
++ Beleuchtung
+++ Blenden vermeiden
+++ direktes Sonnenlicht auf dem Bildschirm vermeiden
-- Bildschirmarbeitsplatz
--- Sauber und aufgeräumt halten
--- Ergonomische Bildschirmhalter
--- Bildschirme damit auf richtiger Höhe
-- Pausen und Bewegung
--- Regelmäßige Pausen durchführen
--- Muskeln und Augen entlasten
--- Dehnübungen sinnvoll einsetzen
-- Tastatur und Maus
--- ergonomische Maus (vertikal)
--- ergonomische Tastatur (Winkel)
-- Schallpegel
--- geringer Geräuschpegel in der Umgebung
--- Stress und Ablenkungen minimieren
-- Organisation
--- häufig verwendete Gegenstände in Reichweite halten
--- unnötige Handlungsabläufe durch Planung vermeiden
@endmindmap