@startuml "Veranstaltungstickets"
left to right direction

actor Customer as "Kunde"
actor Organizer as "Veranstalter"
actor TicketSystem as "Ticket-System"

rectangle "Veranstaltungstickets" {
  usecase "Anmelden" as Anmelden
  usecase "Angebot abrufen" as AngebotAbrufen
  usecase "Bestellhistorie anzeigen" as BestellhistorieAnzeigen
  usecase "Tickets durchsuchen" as TicketsDurchsuchen
  usecase "Veranstaltung erstellen" as VeranstaltungErstellen
  usecase "Tickettypen festlegen" as TickettypenFestlegen
  usecase "Verkaufsberichte einsehen" as VerkaufsberichteEinsehen
  usecase "Ticket kaufen" as TicketKaufen
  usecase "Bestellungsverwaltung" as Bestellungsverwaltung
  usecase "Verfügbarkeit prüfen" as VerfügbarkeitPrüfen
  usecase "Benachrichtigungen senden" as BenachrichtigungSenden
}

Customer -- Anmelden
Organizer -- VeranstaltungErstellen
Organizer -- TickettypenFestlegen
Organizer -- VerkaufsberichteEinsehen
TicketSystem -- Bestellungsverwaltung
TicketSystem -- VerfügbarkeitPrüfen
TicketSystem -- BenachrichtigungSenden

Anmelden <.- AngebotAbrufen : extend
Anmelden <.- BestellhistorieAnzeigen : extend
Anmelden <.- TicketsDurchsuchen : extend
Anmelden <.- TicketKaufen : extend
VerfügbarkeitPrüfen .-> TicketsDurchsuchen : include

@enduml
